name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Build
      run: swift build

    - name: Run Core Tests
      run: swift test --filter SLSCoreTests

    - name: Run All Tests (with timeout)
      run: |
        # Run all tests but with a timeout to prevent hanging
        # Note: Shell completion tests may be skipped if they hang
        swift test --parallel || exit 1
      timeout-minutes: 5
